fos_rest:
  param_fetcher_listener: true
  body_listener: true
  view:
    view_response_listener: true
  serializer:
    serialize_null: true
    groups: ['Default']
  format_listener:
    rules:
      prefer_extension: false
      fallback_format: json