framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: {}

        transports:
            chat_queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    queue_name: chat

        routing:
            'App\AmqpMessages\AmqpChatMessage': chat_queue
