framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: {}

        transports:
            chat_queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    queue_name: chat
            notification_queue:
                dsn: '%env(MESSENGER_NOTIFICATION_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    queue_name: notifications
            game_action_queue:
                dsn: '%env(MESSENGER_GAME_ACTION_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    queue_name: game_action
            command_queue:
                dsn: '%env(MESSENGER_COMMAND_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    queue_name: commands

        routing:
            'App\AmqpMessages\AmqpChatMessage': chat_queue
            'App\AmqpMessages\AmqpNotification': notification_queue
            'App\AmqpMessages\AmqpGameAction': game_action_queue
            'App\Message\ConsoleCommand': command_queue
