nelmio_api_doc:
    documentation:
        info:
            title: Game table
            description: Game table application API
            version: 1.0.1
        securityDefinitions:
            api_key:
                type: apiKey
                description: "Your Json Web Token, dont forget to preprend 'Bearer'"
                name:  Authorization
                in: header
        security:
            - api_key: []
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$)
