version: '3'

services:
    db:
        container_name: db
        image: mysql:8
        ports:
            - 33061:3306
        restart: always
        volumes:
            - ./docker/data/db:/var/lib/mysql:delegated,rw
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: secret
        networks:
            - app

    php:
        container_name: php
        build: docker/php/
        restart: always
        volumes:
            - ./:/var/www/symfony:cached
            - /etc/timezone:/etc/timezone:cached
        networks:
            - app

    nginx:
        container_name: nginx
        image: nginx:1.16.0-alpine
        ports:
            - 8000:80
        restart: always
        volumes:
            - ./:/var/www/symfony:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
        networks:
            - app

    rabbitmq:
        container_name: rabbitmq
        hostname: rabbitmq
        image: rabbitmq:3.8-management-alpine
        environment:
            RABBITMQ_USER: guest
            RABBITMQ_PASSWORD: guest
            RABBITMQ_VHOST: /
        volumes:
            - ./docker/data/rabbitmq:/var/lib/rabbitmq
        ports:
            - 15673:15672
            - 5673:5672
        networks:
            - app

    php-cs-fixer:
        image: unibeautify/php-cs-fixer
        volumes: 
            - ./:/workdir
        working_dir: /workdir

    websockets:
        image: golang:1.14-alpine
        volumes:
            - ./go-server:/go/src/websockets
        working_dir: /go/src/websockets
        command: go run main.go
        environment:
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        ports:
            - 8888:8888
        networks:
            - app
        depends_on:
            - rabbitmq
        restart: on-failure

    front:
        container_name: game-table-front
        build:
            context: front
            dockerfile: Dockerfile
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        networks:
            - app

networks:
    app:
        driver: bridge

volumes:
    data:
        driver: local
