api_login_check:
  path: /api/login_check

gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: App\Controller\Api\TokenController

dashboard:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index
